#!/usr/bin/env python3
"""Write ``.env.family`` for docker compose: tokens, never printed.

Usage::

    python scripts/genenv.py           # refuses if .env.family already exists
    python scripts/genenv.py --force   # replace it

The file is gitignored. Values are 32+ random characters. ``KEYRING_SERVICE_TOKENS``
is built from the same strings written to each consumer's real prefixed variable.
``SETTINGS_API_SERVICES`` is the JSON document settings-api's ``services`` field expects.

This script writes a file and prints a count. It never prints a secret.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import secrets
import sys
from pathlib import Path

META_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = META_ROOT / ".env.family"
MIN_TOKEN_CHARS = 32
MASTER_KEY_BYTES = 32

# Services that call keyring's /v1/internal. Names are KEYRING_SERVICE_TOKENS keys
# (and the audience those services mint). Variables are the names their Settings classes
# actually read.
KEYRING_CONSUMERS: tuple[tuple[str, str], ...] = (
    ("lucy-api", "LUCY_KEYRING_SERVICE_TOKEN"),
    ("media-tool", "MEDIA_TOOL_KEYRING_SERVICE_TOKEN"),
    ("spotify-api", "SPOTIFY_API_KEYRING_SERVICE_TOKEN"),
    ("web-search-api", "WSA_KEYRING_SERVICE_TOKEN"),
    ("environments-api", "ENVAPI_KEYRING_SERVICE_TOKEN"),
)

# settings-api ServiceConfig rows. token_var is the consumer's own prefixed name when
# that service already declares settings_api_token; None means only the grant exists yet.
SETTINGS_GRANTS: tuple[tuple[str, str, tuple[str, ...], str | None], ...] = (
    ("lucy-api", "lucy-api", ("lucy",), "LUCY_SETTINGS_API_TOKEN"),
    ("user-api", "user", ("user",), None),
    ("persona-api", "persona", ("persona",), None),
    ("media-tool", "media-tool", ("media",), "MEDIA_TOOL_SETTINGS_API_TOKEN"),
    ("spotify-api", "spotify-api", ("spotify",), None),
    ("web-search-api", "web-search-api", ("search",), None),
    ("keyring-api", "keyring", ("keyring",), None),
    ("environments-api", "environments-api", ("environments",), None),
)


class AlreadyExistsError(Exception):
    """The output file already exists, or cannot be written."""


def new_token() -> str:
    """URL-safe, longer than the 32-character floor keyring and settings-api enforce."""
    token = secrets.token_urlsafe(32)
    if len(token) < MIN_TOKEN_CHARS:
        msg = "token generator produced a value shorter than the floor"
        raise RuntimeError(msg)
    return token


def new_master_key() -> str:
    """Base64 of 32 random bytes — the shape keyring's ``KEYRING_MASTER_KEY`` requires."""
    return base64.b64encode(os.urandom(MASTER_KEY_BYTES)).decode("ascii")


def build_env() -> dict[str, str]:
    """One dict, insertion-ordered, ready to serialise as ``KEY=value`` lines."""
    env: dict[str, str] = {}

    env["KEYRING_MASTER_KEY"] = new_master_key()
    env["KEYRING_ADMIN_TOKEN"] = new_token()

    keyring_tokens = {name: new_token() for name, _variable in KEYRING_CONSUMERS}
    env["KEYRING_SERVICE_TOKENS"] = json.dumps(keyring_tokens, separators=(",", ":"))
    for name, variable in KEYRING_CONSUMERS:
        env[variable] = keyring_tokens[name]

    grants: dict[str, dict[str, object]] = {}
    for name, audience_prefix, namespaces, token_var in SETTINGS_GRANTS:
        token = new_token()
        grants[name] = {
            "token": token,
            "audience_prefix": audience_prefix,
            "namespaces": list(namespaces),
        }
        if token_var is not None:
            env[token_var] = token
    env["SETTINGS_API_SERVICES"] = json.dumps(grants, separators=(",", ":"))
    return env


def render(env: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/genenv.py for docker compose. Do not commit.",
        "# Re-run with --force to replace. Values are not printed by the generator.",
        "",
    ]
    for key, value in env.items():
        lines.append(f"{key}={value}")
    lines.append("")
    return "\n".join(lines)


def write_env(path: Path, *, force: bool) -> int:
    if path.exists() and not force:
        raise AlreadyExistsError(f"{path.name} already exists; pass --force to replace it")
    env = build_env()
    text = render(env)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8", newline="\n")
    tmp.replace(path)
    return len(env)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Write .env.family with random service tokens for docker compose.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace an existing .env.family",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="path to write (default: .env.family in the family root)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    path = args.output if args.output.is_absolute() else (Path.cwd() / args.output)
    try:
        count = write_env(path, force=args.force)
    except AlreadyExistsError as exc:
        print(f"genenv: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"genenv: cannot write {path.name}: {exc.strerror}", file=sys.stderr)
        return 1
    print(f"Wrote {count} variables to {path.name}. Re-run with --force to replace it.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
