#!/usr/bin/env python3
"""Record, and check, the commit each sibling repository was last verified at.

Usage::

    python scripts/lockrepos.py            # check the checkouts against repos.lock
    python scripts/lockrepos.py --write    # record where they are now
    python scripts/lockrepos.py --json     # the same check, as JSON

``repos.txt`` names a folder and a clone URL and says nothing about *which commit*. So "the
family" is whatever each checkout happens to be at: two people running ``make up`` can build
materially different images from the same manifest, and a compose run that worked yesterday
cannot be reproduced today. ``repos.lock`` closes that by recording a commit per repository,
the way a dependency lock does for a package manager.

What it is not: a submodule, and not a thing that pins what you may check out. Nothing here
moves a checkout. It reports drift, and ``--write`` records the set you have just verified
together -- so the lock means "these nine passed as a family", which is the only claim worth
making about a multi-repository project.

Private repositories are deliberately absent. ``.repos.local.txt`` is gitignored because a
public repository must never name a private one (ADR-0011), and a lock file naming one would
leak it in exactly the same way. Only ``repos.txt`` is read.

Standard library only, so it runs before any repository has a virtualenv. Exit status: 0 when
every checkout matches, 1 when any has drifted or is missing, 2 for a usage error.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

META_ROOT = Path(__file__).resolve().parent.parent
REPOS_FILE = META_ROOT / "repos.txt"
LOCK_FILE = META_ROOT / "repos.lock"

HEADER = (
    "# Generated by scripts/lockrepos.py. One line per repository: <folder> <commit>.\n"
    "# The commit each sibling was at when the family was last verified together.\n"
    "# Re-record with `make lock` after a green `make up`; check with `make lock-check`.\n"
    "# Private repositories are never listed here: see docs/adr/"
    "0011-private-services-are-extensions.md.\n"
)

SHA_LENGTH = 40


class LockError(RuntimeError):
    """The manifest or the lock cannot be used as given."""


@dataclass(frozen=True, slots=True)
class Drift:
    """One repository that does not match the lock."""

    name: str
    locked: str
    actual: str
    reason: str

    def line(self) -> str:
        return f"{self.name:<20} {self.reason}"


def read_manifest(path: Path = REPOS_FILE) -> list[str]:
    """Folder names from ``repos.txt``; blank lines and ``#`` comments are skipped."""
    if not path.is_file():
        raise LockError(f"{path.name} is missing")
    names: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        names.append(line.split()[0])
    return names


def read_lock(path: Path = LOCK_FILE) -> dict[str, str]:
    """Folder to commit. A missing file is an empty lock, not an error."""
    if not path.is_file():
        return {}
    locked: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            raise LockError(f"{path.name}: expected '<folder> <commit>', found {line!r}")
        locked[parts[0]] = parts[1]
    return locked


def head_of(repo: Path) -> str:
    """The checkout's current commit, or `""` when it is not a git repository."""
    if not (repo / ".git").exists():
        return ""
    # A fixed argv, no shell, and nothing from a person reaches it.
    finished = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    )
    return finished.stdout.strip() if finished.returncode == 0 else ""


def compare(names: list[str], locked: dict[str, str], root: Path) -> list[Drift]:
    """Every repository that does not match the lock, with what is wrong about it."""
    drifts: list[Drift] = []
    for name in names:
        want = locked.get(name, "")
        have = head_of(root / name)
        if not want:
            drifts.append(Drift(name, "", have, "not in repos.lock; run `make lock`"))
        elif not have:
            drifts.append(Drift(name, want, "", "no checkout here"))
        elif want != have:
            drifts.append(Drift(name, want, have, f"locked {want[:12]}, checkout {have[:12]}"))
    drifts.extend(
        Drift(name, locked[name], "", "in repos.lock but not in repos.txt")
        for name in sorted(set(locked) - set(names))
    )
    return drifts


def render(names: list[str], root: Path) -> str:
    """The lock file's contents for the checkouts as they are now."""
    lines = [HEADER]
    for name in names:
        head = head_of(root / name)
        if not head:
            raise LockError(f"{name} has no checkout to record; clone it first")
        lines.append(f"{name} {head}\n")
    return "".join(lines)


def write(names: list[str], root: Path, path: Path = LOCK_FILE) -> int:
    path.write_text(render(names, root), encoding="utf-8", newline="\n")
    return len(names)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help="record the current commits")
    parser.add_argument("--json", action="store_true", help="report as JSON")
    parser.add_argument("--repos-file", type=Path, default=REPOS_FILE)
    parser.add_argument("--lock-file", type=Path, default=LOCK_FILE)
    args = parser.parse_args(argv)

    root = args.repos_file.resolve().parent
    try:
        names = read_manifest(args.repos_file)
        if args.write:
            count = write(names, root, args.lock_file)
            print(f"Recorded {count} repositories in {args.lock_file.name}.")
            return 0
        drifts = compare(names, read_lock(args.lock_file), root)
    except LockError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.json:
        print(json.dumps([asdict(d) for d in drifts], indent=2))
    elif drifts:
        print(f"{len(drifts)} repository(s) differ from {args.lock_file.name}:\n")
        for drift in drifts:
            print(f"  {drift.line()}")
        print("\nRe-record with `make lock` once the family passes together.")
    else:
        print(f"All {len(names)} repositories match {args.lock_file.name}.")
    return 1 if drifts else 0


if __name__ == "__main__":
    raise SystemExit(main())
